"""Adicionando cascata e revisando o erro

Revision ID: b02ec64f10d1
Revises: 39c6b8a00490
Create Date: 2026-05-05 11:03:39.930469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02ec64f10d1'
down_revision: Union[str, Sequence[str], None] = '39c6b8a00490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_biblioteca_jogo_id'), 'biblioteca', ['jogo_id'], unique=False)
    op.create_index(op.f('ix_biblioteca_usuario_id'), 'biblioteca', ['usuario_id'], unique=False)
    op.drop_constraint(None, 'biblioteca', type_='foreignkey')
    op.drop_constraint(None, 'biblioteca', type_='foreignkey')
    op.create_foreign_key(None, 'biblioteca', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'biblioteca', 'jogos', ['jogo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'biblioteca', type_='foreignkey')
    op.drop_constraint(None, 'biblioteca', type_='foreignkey')
    op.create_foreign_key(None, 'biblioteca', 'jogos', ['jogo_id'], ['id'])
    op.create_foreign_key(None, 'biblioteca', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_biblioteca_usuario_id'), table_name='biblioteca')
    op.drop_index(op.f('ix_biblioteca_jogo_id'), table_name='biblioteca')
    # ### end Alembic commands ###
